services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: hoang/123
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
